apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bytestash.fullname" . }}
  labels:
    {{- include "bytestash.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bytestash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bytestash.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bytestash.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if eq .Values.ingress.path "/" }}
          - name: BASE_PATH
            value: ""
          {{- else }}
          - name: BASE_PATH
            value: {{ .Values.ingress.path | quote }}
          {{- end }}
          {{- with .Values.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- range $key, $value := .Values.extraEnvSecrets }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $value.name | quote }}
                key: {{ $value.key | quote }}
          {{- end }}
          {{- if and ( .Values.authentication.enabled) ( eq .Values.authentication.existingAuthSecrets.secretName "" ) }}
          - name: AUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ include "bytestash.fullname" . }}-auth
                key: "AUTH_USERNAME"
          - name: AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "bytestash.fullname" . }}-auth
                key: "AUTH_PASSWORD"
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "bytestash.fullname" . }}-auth
                key: "JWT_SECRET"
          - name: TOKEN_EXPIRY
            value: {{ .Values.authentication.expirity | quote }}
          {{- else if and ( .Values.authentication.enabled) ( ne .Values.authentication.existingAuthSecrets.secretName "" ) }}
          - name: AUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.authentication.existingAuthSecrets.secretName | quote }}
                key: {{ .Values.authentication.existingAuthSecrets.userKey | quote }}
          - name: AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.authentication.existingAuthSecrets.secretName | quote }}
                key: {{ .Values.authentication.existingAuthSecrets.pwdKey | quote }}
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.authentication.existingAuthSecrets.secretName | quote }}
                key: {{ .Values.authentication.existingAuthSecrets.jwtKey | quote }}
          - name: TOKEN_EXPIRY
            value: {{ .Values.authentication.expirity | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.ingress.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.ingress.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: snippets
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "bytestash.fullname" . }}-data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
