{{- if and ( .Values.authentication.enabled) ( eq .Values.authentication.existingAuthSecrets.secretName "" ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bytestash.fullname" . }}-auth
  labels:
    {{- include "bytestash.labels" . | nindent 4 }}
data:
  AUTH_USERNAME: {{ .Values.authentication.username | b64enc | default "" }}
  AUTH_PASSWORD: {{ .Values.authentication.password | b64enc | default "" }}
  JWT_SECRET: {{ .Values.authentication.jwt | b64enc | default "" }}
{{- end }}
