apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swagger.fullname" . }}
  labels:
    {{- include "swagger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.swaggerui.replicaCount }}
  selector:
    matchLabels:
      {{- include "swagger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.swaggerui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "swagger.labels" . | nindent 8 }}
	      {{- with .Values.swaggerui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.swaggerui.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "swagger.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.swaggerui.podSecurityContext | nindent 8 }}
      {{- if .Values.swaggerui.swagger_config_s3.enabled }}
      initContainers:
        - name: init-downloader
          image: "{{ .Values.swaggerui.swagger_config_s3.image.repository }}:{{ .Values.swaggerui.swagger_config_s3.image.tag }}"
          imagePullPolicy: {{ .Values.swaggerui.swagger_config_s3.image.pullPolicy }}
          command: ["sh", "-c"]
          args: {{ (printf "[\"aws s3 cp %s/%s /api-doc\"]" .Values.swaggerui.swagger_config_s3.s3_bucket_uri .Values.swaggerui.swagger_config_s3.s3_config_object) }}
          volumeMounts:
          - mountPath: /api-doc
            name: swagger-config
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.swaggerui.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.swaggerui.image.repository }}:{{ .Values.swaggerui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.swaggerui.image.pullPolicy }}
          volumeMounts:
          - mountPath: /api-doc
            name: swagger-config
          {{- if $.Values.swaggerui.swagger_config_local }}
          - mountPath: /api-doc/local-config
            name: local-config
          {{- end }}
          env:
          {{- with .Values.swaggerui.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.swaggerui.apikey }}
          - name: API_KEY
            value: {{ . | quote }}
          {{- end }}
          {{- with .Values.swaggerui.service.port  }}
          - name: PORT
            value: {{ . | quote }}
          {{- end }}
          {{- with .Values.swaggerui.service.port  }}
          - name: PORT_IPV6
            value: {{ . | quote }}
          {{- end }}
          {{- with .Values.swaggerui.base_url }}
          - name: BASE_URL
            value: {{ . | quote }}
          {{- end }}
          {{- with .Values.swaggerui.enable_cors }}
          - name: CORS
            value: {{ . | quote }}
          {{- end }}
          - name: EMBEDDING
            value: {{ .Values.swaggerui.allow_embedding | quote }}
          {{- if .Values.swaggerui.disable_validation }}
          - name: VALIDATOR_URL
            value: "localhost"
          {{- else if and ( not .Values.swaggerui.disable_validation ) ( not .Values.localValidation.enabled ) }}
          - name: VALIDATOR_URL
            value: "https://validator.swagger.io/validator"
          {{- else }}
          {{- if .Values.localValidation.ingress.enabled }}
          - name: VALIDATOR_URL
            value: http://{{ .Values.localValidation.ingress.host }}/validator
          {{- else }}
          - name: VALIDATOR_URL
            value: http://swagger-validator:8080/validator
          {{- end }}
          {{- end }}
          {{- if and .Values.swaggerui.swagger_config_s3.enabled }}
          - name: SWAGGER_JSON
            value: /api-doc/{{ .Values.swaggerui.swagger_config_s3.file_name }}
          - name: AWS_REGION
            value: {{ .Values.swaggerui.swagger_config_s3.aws_region }}
          {{- else if and (not .Values.swaggerui.swagger_config_s3.enabled) ($.Values.swaggerui.swagger_config_local) }}
          - name: SWAGGER_JSON
            value: /api-doc/local-config/swagger.json
          {{- else }}
          - name: SWAGGER_JSON_URL
            value: {{ .Values.swaggerui.swagger_config_public | quote }}
          {{- end }}
          {{- if $.Values.swaggerui.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.swaggerui.livenessProbe.httpGet.path }}
              port: {{ .Values.swaggerui.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.swaggerui.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.swaggerui.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.swaggerui.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.swaggerui.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.swaggerui.livenessProbe.successThreshold }}
          {{- end }}
          {{- if $.Values.swaggerui.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.swaggerui.readinessProbe.httpGet.path }}
              port: {{ .Values.swaggerui.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.swaggerui.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.swaggerui.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.swaggerui.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.swaggerui.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.swaggerui.readinessProbe.successThreshold }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.swaggerui.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.swaggerui.resources | nindent 12 }}
      {{- with .Values.swaggerui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.swaggerui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.swaggerui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: swagger-config
          emptyDir: {}
        {{- if $.Values.swaggerui.swagger_config_local }}
        - name: local-config
          secret:
            secretName: {{ $.Values.swaggerui.swagger_config_local }}
        {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swagger.fullname" . }}-validator
  labels:
    {{- include "swaggervalidator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "swaggervalidator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.localValidation.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "swaggervalidator.labels" . | nindent 8 }}
	      {{- with .Values.localValidation.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.localValidation.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.localValidation.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-validator
          securityContext:
            {{- toYaml .Values.localValidation.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.localValidation.image.repository }}:{{ .Values.localValidation.image.tag }}"
          imagePullPolicy: {{ .Values.localValidation.image.pullPolicy }}
          env:
          {{- with .Values.localValidation.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          - name: REJECT_LOCAL
            value: "false"
          - name: REJECT_REDIRECT
            value: "false"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.localValidation.resources | nindent 12 }}
      {{- with .Values.localValidation.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.localValidation.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.localValidation.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
