{{- if .Values.swaggerui.ingress.enabled -}}
{{- $fullName := include "swagger.fullname" . -}}
{{- $svcPort := .Values.swaggerui.service.port -}}
{{- if and .Values.swaggerui.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.swaggerui.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.swaggerui.ingress.annotations "kubernetes.io/ingress.class" .Values.swaggerui.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "swagger.labels" . | nindent 4 }}
  {{- with .Values.swaggerui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.swaggerui.ingress.className }}
  {{- if .Values.swaggerui.ingress.tls }}
  tls:
    {{- range .Values.swaggerui.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.swaggerui.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.swaggerui.ingress.path }}
            pathType: {{ .Values.swaggerui.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
---
{{- if .Values.localValidation.ingress.enabled -}}
{{- if and .Values.localValidation.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.localValidation.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.localValidation.ingress.annotations "kubernetes.io/ingress.class" .Values.localValidation.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: swagger-validator
  labels:
    {{- include "swaggervalidator.labels" . | nindent 4 }}
  {{- with .Values.localValidation.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.localValidation.ingress.className }}
  {{- if .Values.localValidation.ingress.tls }}
  tls:
    {{- range .Values.localValidation.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}.
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.localValidation.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.localValidation.ingress.path }}
            pathType: {{ .Values.localValidation.ingress.pathType }}
            backend:
              service:
                name: swagger-validator
                port:
                  number: 8080
{{- end }}
