apiVersion: v1
kind: Service
metadata:
  name: {{ include "swagger.fullname" . }}
  labels:
    {{- include "swagger.labels" . | nindent 4 }}
{{- if .Values.swaggerui.service.annotations }}
  annotations:
{{ toYaml .Values.swaggerui.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.swaggerui.service.type }}
  {{- if .Values.swaggerui.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.swaggerui.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.swaggerui.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
  {{- end }}
  {{- if .Values.swaggerui.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.swaggerui.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.swaggerui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "swagger.selectorLabels" . | nindent 4 }}
---
{{- if $.Values.localValidation.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "swagger.fullname" . }}-validator
  labels:
    {{- include "swaggervalidator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.localValidation.serviceType }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "swaggervalidator.selectorLabels" . | nindent 4 }}
{{- end }}
