apiVersion: v1
kind: Service
metadata:
  name: {{ include "otlpdemo.fullname" . }}-dbservice
  labels:
    {{- include "dbservice.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5050
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dbservice.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otlpdemo.fullname" . }}-dbservice
  labels:
    {{- include "dbservice.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dbservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: {{ .Values.instrumentation }}
      labels:
        {{- include "dbservice.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "otlpdemo.fullname" . }}-dbservice
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.backends.dbservice.repository }}:{{ .Values.backends.dbservice.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_CONNECTION
              value: "Server={{ include "otlpdemo.fullname" . }}-mssql,1433;User=sa;Password=P@ssw0rd1111;TrustServerCertificate=True;"
          ports:
            - name: http
              containerPort: 5050
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
