{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dashy.serviceAccountName" . }}
  labels:
    {{- include "dashy.labels" . | nindent 4 }}

  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

    {{- if .Values.localIconfromS3.enabled }}
    {{- with .Values.localIconfromS3.irsa }}
    eks.amazonaws.com/role-arn: {{ . | quote }}
    {{- end }}
    {{- end }}
{{- end }}
