apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dashy.fullname" . }}-conf
  labels:
    {{- include "dashy.labels" . | nindent 4 }}
data:
  {{- toJson .Values.staticConfigurations | nindent 2 }}
