apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "statping.fullname" . }}-services
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "statping.labels" . | nindent 4 }}
{{- if .Values.customServiceConfigs }}
data:
  services.yml: |-
    {{- toYaml .Values.customServiceConfigs | nindent 4}}
{{- else }}
data:
  services.yml: |
    x-httpservice: &httpservice
      type: http
      method: GET
      check_interval: 45
      timeout: 10
      expected_status: 200
      allow_notifications: true
      notify_after: 2
      notify_all_changes: true
      public: true
      redirect: true

    x-tcpservice: &tcpservice
      type: tcp
      check_interval: 60
      timeout: 15
      allow_notifications: true
      notify_after: 0
      notify_all_changes: true
      public: true
      redirect: true

    services:
      {{- range $index, $value := .Values.httpServices }}
      - name: {{ $value.name }}
        domain: {{ $value.domain }}
        <<: *httpservice
      {{- end }}
      {{- range $index, $value := .Values.tcpServices }}
      - name: {{ $value.name }}
        domain: {{ $value.domain }}
        <<: *tcpservice
      {{- end }}
{{ end }}
