{{- if .Values.envConfigs -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "statping.fullname" . }}-configs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "statping.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.envConfigs | nindent 2 }}
{{- end -}}
